sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: make travis-install
script: make travis-script
after_success: codeclimate-test-reporter
deploy:
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: Andrew.Hawker
  password:
    secure: OrSxL2aXbTv/yO9IIdrSOF6oV4R9b+z4q0f8xA7xb2rdbNDVZ+IUlJgT0f8B+No8WwoLMleKIPzZnb0w6PtKW23+ygEKB9204qNqHmRFCs8guVznz/g4R9qa8on9O0B9y6SoODQuRxwde/KcJHfQNeNiPLIH3FpNDuGOgaLFqxAaYz3axj3KJdjFSLec/yJkjFdrp+2MTYgIbbtrxwHUWhXuhyj6kWmtrtxiQwY8p8IX7Ni0cBv6ke/jsYcN+YjpMhDCHoxuCTgnlGBhv8UgtDleaX8tKIB1s8CsTZOc4zYtwUWYphzpjdFySHXDieSHuwQdvykYea9aEI19QqtUUtY9u/Hlg3+pSZQyBJRiAk1CPydQaaF4mxBrwzXFXvczwQTXE5fv8x5vAWFBtnVQBeffkk/4Z31kPHOYrIi3KK48mZK4CbMlM6Aabg8DIovdd9vxYcXTRS4pt8aH7T06V6iqcHxRqrLnvDE77QH/LEBbuMumFDbGphNLkaw7DB40yJPa1P2cceqoTXQWF3fYmHovAA57gvLTETCCncw2gfki7wyCTRKjhuaScmQqPHqEVyZ20YEvbJ3Z4rhKcwxUBkRhrzmtUITGYqxICkPHDiTenu1J45elk6JSQT2fN9fMq6Cup3qt3QbDxHWyTRxlbQAiWskgwdf27TqMVHPUFL8=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "3.4"
- provider: pypi
  server: https://pypi.python.org/pypi
  user: Andrew.Hawker
  password:
    secure: cdL7TSNlbxpCP+lZUd8XMOA6OnrO0xx8qSO8ZugFgNRXAyA4YAXeUoyV7MLmEBIc7Q+AsHHo2Lzqwo7EXQPtgstfwbcEDl7k1IWSM3BwPSTMIVSn5Ndar9aIFMdHy1Ql7aikIrRPlLc8gtsDImeYLuwCqZQc/XYl9wc43Xfv4wLmQj4bJ0GBVNyTQ9oXqMmRRtm/67DwF0rR3WHZGPcNjmXRgM1nY2Tx2ZM0/bBapRTsJYaKis/xTZwvZlx+5UpYeZa6+HR2mYK8aAPut5f65IhDGKyKzJeGZ8rTs5q5XESFGENBlIwJnOIENtvJ8xk2kyjlldY2z67kRVjP9suXErfb2kLI3fDDsS09JXTdg+/yfY6SK7P5SpchP91KD9qNLLcNBOAmAVca+k1fBUctX18W7sYfphSMY7VRqozQ4mwVlnqEfh8MZaswYaJA6SYmcXphnxBXWwpvhIIg/3HVOStj5JGMOQe582AFYT6OIPp1pXDmdN21lshEDT3G+unci4VVYqDRdtMUy81O5aYYhN8KXLwLR/vIHoib1j7LkAtL4Aq5sIcHhFFtg4cQobRjGwFuBW9vQm2ATUO9XzbbsBD7nsVkXOoa4N7uz7G+UQgyqV6C+tiyVR10slMJeiIBiO8lURvxFU5HoYtct55ZHD6N7h3oWcly9vB7lsUMAQg=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.4"
notifications:
  slack:
    secure: oKKmL6XY+yHBqkf65sh63cXeMTElrVtgqeVoLbXUTU4/nScub1YdXjoe7/xTfJqJi2hW9rzDtdoPi9v+mqDJ3tMF5bbUM5i8n1IPwP1bqKyHanqzdAQXeCPw2VtFYAZG85i8ewbxyi4C/LepgIihnP/2T9KeMvK6174v+jJMO0gcEqPOE8J0qq1uSOXg4nd3R58Lv5AVhKyx3z7QmGqpi46uHI8TwhqSi3P8ZdY1gL7lIUkwPZaEAKVdM8K31CJm05T6Eb8eAv4IcynQG1UGghCk9GlCeUcb+/MRwILAmazM10QoMaHIhouzyE+U1hppCvxBwNYznk61bLu5mxYldQsdDsRr2KBN1eN6PeNiH8r5w9+l0OVjNEh6iNlHZErcJdUs7qw3Q2xoEzXqkmCSAvDi0aaIbvL98pRGLFqGi0LcCc/Rdo4qNaHr9tAwUy26S3P81G7fWRNs7x07G4bNT0pDBtuW1v1bsesJHQv9SkRc4KULBK0+yMIW4rHveAmKSm44SpiHq1D3mm9NiVUJ7TLp66gPfQyBbSoZtT4ievxix5VHEPnxB8sCVCeRo0xbExkdMno+Zb4WipLKs9A8E+xzhc5zFHwC/k2+9F/shv/6avvMS50ndAXfCFUaYCb5r0kZqTxJXEKSxgpOThIB5p3Y2UGi02EBodpVqwq+pZE=
env:
  matrix:
    secure: M+eU49GlVd5Pr7nPqMDQxoelGvV0bUkILGBAd8dIrePpJDmBqwTy6rRem4qXOq/gn/Q/L5VEEiJmuO0uhV4ECACNIpk94iUMoExbjl0BeBocg0joY5kMlLqx76xlEbUkfO+2KpyosITP96tcdOIaU9dTW9FzxvOmslXFDpJ5OcyJG5uCpyeDex8xSRQcVQMpD9LIc/kGxlibzVc/tOawqX4sfzSX1WtlrgCJXiVu9eTvYPG9t8TRiLclWxyKIDY2D0CleD0ys3OuLnHf5WD3IdeBYKuTedDCDijF18BDwT/c8M+evQfw1+gfKgmmbl617VW3n8zGwIt6KlpkPbcHTp9M6tAK+HWBBg/YE67e2FwDo3Cy4dqRKVIaCm2Pd2SAbJYYxRMHd/FRU9DVXZ3XR1PYN1Oak+1u7q2mPAFO0WeRAj5rV4iURM2/nh8/dhqMpbDaC18bNQSJvPHFwz8hK+GEQBkzGziVs6tEKO5f8CqDTLpQEDpl2GtJaeFpDrXwxEDIFM2dT/+C0q6ZTiBwLvsVcWuO5kbPlylv/v/Z5HmsM2b0eon1rk7fpdAmmXL+Ld7Hf3ZNCw0HsFbTahuWeoXtZJCkRsxG0oAEi9O5VvwgjA9PQKyNTnuz+bURYV5OUWYITxzEJHWsl8GsrMraARAUND8FM+SCmvlwpax0B8o=
