sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: make travis-install
script: make travis-script
after_success: codeclimate-test-reporter
deploy:
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: Andrew.Hawker
  password:
    secure: FPuakAcW9rxQZf4MSfscgbDfzf4FuwtlTw4rLN1lbOTSDa2/QTA9LeuFxv/SFXAttH1Jzyh9a1qCnRibq60ndzrEvKX7DODTjs4mJ3NaIhJDLTXC8wckPMsjwgO+Pwfsh7smjuHzAEoP6I2HNFO9Xu0lZhhdL08nmdG6Al8Id1sv4SiFcE72usYtVIvmD+MxpwyyCclJK75kH2v7HiLGRm8paZeo7ARw+xhHpAw6UE4PUjNBl274vLaYwGQhurwTM7TANye/EQpV/l6R7ke8O6wMlUykBhL7Z1aiyOMO7dVlQo5NozBM848Y6cF+Bn6KKBw/H1CA1XU8H0SySTtPpJsu2SCX1lNLt0aXkvQYcGWbBz6R7pcDhpulHxDWjwWz3R96/iPBRkwyJrwNph+TP6E2md/climFsXbf85yTSOZKALORRIATTfR9l0+6yizxixG19Mc96CPRQNe+9P1NeGaX0eJmgLwOQ//eOE8iTLiPG4AXvkF4FqgFtO0KvHmVLa053fOzsEUdyUPpnZByDW7WO5Fj0zzx4PzH8SO6c9fMyNOB7RpKzU17sdawcOkFDXVT6GFkKJesu8bf6I2v/TJuCKOtcVUPeJpww+X/PRjRiXwxnUhGkbj7sPW3lfblwGbCNG+m7RYkueFBJiumrsYqXMAyON+GA+v6EUIMvTs=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "3.4"
- provider: pypi
  server: https://pypi.python.org/pypi
  user: Andrew.Hawker
  password:
    secure: eVd8Zb1S48TAnIbPktCc7SGKQlugRLUv2+77CywblVC1lSZi6IrJiNbsg9E8cMInoOA2GeqlJ/ywrrqP0LVIm1Uqht3YzDyUMFioUIsHnX86M7Lhpb7Yf4++Iig4aEPmrzXe8B7/4Lq9958pjneQl4snUo+ji1ma81p7py6unIPbEZkoVvo4Hb9x5wKUIOL7O6UZsMplBo5/csQfI0IjoCRox9Rfbylda2xFWHj8GJLn5jAEP/nv17pmIwGU75u5FeWdjLKL4YQmIKIuLGRSO9Jwvrm1US8IRBL/xK2+MsGtdKNmEHtx0kehLr2t8yC0KsSw07m3Tl9id0TP+Q7b5+FIg3FnVhu2+eXBg1+2rI7eOLBEMyiwd49dTeSLAFXnHBLTywIEcRfapETjrAldxJZ20Zh6Lp2/qY0H9kYoeM8MswwhqqQA1tqlbkwnPsiEI5iT3ABToHTKX6H7xbZ48vkgTFVlELjfRL56r7lidkiogVm6yf19vsRTcKlG9wPt2Y51VHtH2CRy96N9MoPQtZmLkmqiM1wd1/wXjrOtDNSGb8F4n+ip+/mIJetcxvpHagXu/jkkfdQvJ5eWoNTt54Gviox9En5l+uQ6lWfgNgdBCRwmtQftrFBNcAcfizVXFXYFVvESGCUVDfkD/N14MkqJC1N7QsAPs9AeDS7cmfc=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.4"
notifications:
  slack:
    secure: oKKmL6XY+yHBqkf65sh63cXeMTElrVtgqeVoLbXUTU4/nScub1YdXjoe7/xTfJqJi2hW9rzDtdoPi9v+mqDJ3tMF5bbUM5i8n1IPwP1bqKyHanqzdAQXeCPw2VtFYAZG85i8ewbxyi4C/LepgIihnP/2T9KeMvK6174v+jJMO0gcEqPOE8J0qq1uSOXg4nd3R58Lv5AVhKyx3z7QmGqpi46uHI8TwhqSi3P8ZdY1gL7lIUkwPZaEAKVdM8K31CJm05T6Eb8eAv4IcynQG1UGghCk9GlCeUcb+/MRwILAmazM10QoMaHIhouzyE+U1hppCvxBwNYznk61bLu5mxYldQsdDsRr2KBN1eN6PeNiH8r5w9+l0OVjNEh6iNlHZErcJdUs7qw3Q2xoEzXqkmCSAvDi0aaIbvL98pRGLFqGi0LcCc/Rdo4qNaHr9tAwUy26S3P81G7fWRNs7x07G4bNT0pDBtuW1v1bsesJHQv9SkRc4KULBK0+yMIW4rHveAmKSm44SpiHq1D3mm9NiVUJ7TLp66gPfQyBbSoZtT4ievxix5VHEPnxB8sCVCeRo0xbExkdMno+Zb4WipLKs9A8E+xzhc5zFHwC/k2+9F/shv/6avvMS50ndAXfCFUaYCb5r0kZqTxJXEKSxgpOThIB5p3Y2UGi02EBodpVqwq+pZE=
